### ISSUE TITLE
question

### ISSUE THREAD

**Issue by toyg** [jpsk/Swedbank-to-YNAB4-converter#1]
Hi, I'm one of the developers of another converter of files for YNAB, https://github.com/torbengb/bank2ynab/ . We'd like to incorporate this converter as plugin in our repo, would that be ok with you?

It would be great if you could also send us a test input file as well so that we can keep it for tests (of course you can remove any sensitive info, we only need the structure). Feel free to ping me on the email on my profile, or open an issue at https://github.com/torbengb/bank2ynab/issues/

Thanks!

**Comment by jpsk** [comment]
Hi, @toyg,
I have added MIT license, so feel free to use for your project. I have also added two sample input files. Strangely, when requesting .csv from swedbank, the downloaded file has .xls file extension, so I have included both _statement.csv_ and _statement.csv.xls_. 
I hope this will help.
